### PR TITLE
Avoid cloning in Selectors

### PR DESCRIPTION
**Pull request by Gachapen**
Improves performance (amount depending on Phenotype implementation).

### CODE REVIEW

**Comment by m-decoster** [comment]
These changes have opened my eyes to some other potential optimizations, which unfortunately would require a breaking change to the API.

I'll review this PR when I have some more time, but it looks good.

**Comment by Gachapen** [comment]
_Edit: I just saw your commit changing the parents to references_ 😃

@m-decoster I actually made some more changes to improve performance and flexibility, but was reluctant to create a PR because it breaks the API. If interested, see here: https://github.com/Gachapen/RsGenetic/commit/c72e203298bc00fade903bc3b00981c1811ed8b3 (you could make the parents into references without changing the tuples to single variables, but I needed both for my application). I made the changes so that I could make my own `Simulator` even more flexible (e.g. allowing custom genetic operators such as pruning and duplication, or just variations of crossover and mutation).

I'm interested in changing the API to be more flexible, potentially merging it back here or creating a new crate (the changes would probably be drastic), if I can find time for it. What do you think?

**Comment by m-decoster** [comment]
@Gachapen I understand your concern for breaking the API, but those selectors are only to be used by the library itself anyway (and should have been abstracted/hidden away before version 1.0.0, in hindsight. The whole library could use a redesign). Since your commit has some other improvements, feel free to create another PR.

I created this crate when I was still a Rust beginner. I would do a lot of things differently now. I think a version 2.0 is overdue, or perhaps a new crate. There are some other alternatives too, just check out [darwin-rs](https://crates.io/crates/darwin-rs) for example. If those alternatives do not suit your need, I would be willing to cooperate on RsGenetic 2.0 or on a new crate. In my case this is also *if I can find time for it.*

*Edit: now that I think of it, it could be useful to separate this into a second crate. Your use case clearly requires more interaction with the "framework", such as a custom `Simulator`, pruning, etc. RsGenetic was mostly designed to be easy to use and plug-and-play for simple problems. A new version of RsGenetic could be based on a lower-level crate, which would also suit your needs.*

**Comment by Gachapen** [comment]
@m-decoster I see, that makes sense. I agree with you that my use case requires a more low-level crate (darwin-rs is not good enough, though interesting), and I like your idea of building RsGenetic or some other plug-and-play crate on top of that. I'll come back to you if I start on something 👍

**Pull request merged**
